### PR TITLE
Fix/dependency enrich error

### LINKED ISSUE #91: Fix return error when value doesn't exist on brick.yml
at the moment it is ignored we should return an error(set brick.EnrichError) and display a warning

### PR DESCRIPTION
**Pull request by half-shell**
Changes:
* fixes #91
* fix example infra `user-and-groups` naming to match the dependencies 
* Improve error display by adding a line jump
* change configuration path's name to be more explicit. Replace `Configuration.ConfigurationFile` with `Configuration.ConfigurationFilePath`

### CODE REVIEW

File: src/infra/infra.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ func CreateInfra(configuration exargs.Configuration) (Infra, error) {
 	for name, path := range configuration.Rooms {
 		b, err := GetBricks(name, path)
 		if err != nil {
-			fmt.Printf(`Cannot add "%s" (path: %s) room's bricks: %s`, name, path, err)
+			fmt.Printf("Cannot add \"%s\" (path: %s) room's bricks: %s\n", name, path, err)
```
Comment (arthur91f) [inline src/infra/infra.go:44]: fmt.Printf("Cannot add \"%s\" (path: %s) room's bricks: %v\n", name, path, err)

The last %s should be %v

Comment (half-shell) [reply src/infra/infra.go:44]: I looked it up 'cause I wasn't sure it's that clear cut, especially considering it works. But I think it's up for debate: https://stackoverflow.com/questions/43887776/what-is-the-correct-format-specifier-to-print-error-object-in-go-s-or-v

However, considering that's how we do it in most of the other code, I'm fine with the change, sure :ok_hand:

**Review by arthur91f — APPROVED** [review]
